INSERT INTO SportCategorie (nom, nom_anglais, sexe, is_individual, id_Sport) VALUES
('100m', '100 metres', 'Homme', True, 1),
('200m', '200 metres', 'Homme', True, 1),
('400m', '400 metres', 'Homme', True, 1),
('800m', '800 metres', 'Homme', True, 1),
('1500m', '1,500 metres', 'Homme', True, 1),
('5000m', '5,000 metres', 'Homme', True, 1),
('10000m', '10,000 metres', 'Homme', True, 1),
('Marathon', 'Marathon', 'Homme', True, 1),
('110m haies', '110 metres Hurdles', 'Homme', True, 1),
('400m haies', '400 metres Hurdles', 'Homme', True, 1),
('3000m steeple', '3,000 metres Steeplechase', 'Homme', True, 1),
('4x100m', '4 × 100 metres Relay', 'Homme', False, 1),   
('4x400m', '4 × 400 metres Relay', 'Homme', False, 1),   
('20km marche', '20 kilometres Race Walk', 'Homme', True, 1),  
('50km marche', '50 kilometres Race Walk', 'Homme', True, 1),  
('Hauteur', 'High Jump', 'Homme', True, 1),
('Perche', 'Pole Vault', 'Homme', True, 1),
('Longueur', 'Long Jump', 'Homme', True, 1),
('Triple saut', 'Triple Jump', 'Homme', True, 1),
('Poids', 'Shot Put', 'Homme', True, 1),
('Disque', 'Discus Throw', 'Homme', True, 1),
('Marteau', 'Hammer Throw', 'Homme', True, 1),
('Javelot', 'Javelin Throw', 'Homme', True, 1),
('Décathlon', 'Decathlon', 'Homme', True, 1),
('100m', '100 metres', 'Femme', True, 1),
('200m', '200 metres', 'Femme', True, 1),
('400m', '400 metres', 'Femme', True, 1),
('800m', '800 metres', 'Femme', True, 1),
('1500m', '1,500 metres', 'Femme', True, 1),
('5000m', '5,000 metres', 'Femme', True, 1),
('10000m', '10,000 metres', 'Femme', True, 1),
('Marathon', 'Marathon', 'Femme', True, 1),
('100m haies', '100 metres Hurdles', 'Femme', True, 1),
('400m haies', '400 metres Hurdles', 'Femme', True, 1),
('3000m steeple', '3,000 metres Steeplechase', 'Femme', True, 1),
('4x100m', '4 × 100 metres Relay', 'Femme', False, 1),
('4x400m', '4 × 400 metres Relay', 'Femme', False, 1),
('20km marche', '20 kilometres Race Walk', 'Femme', True, 1),
('Hauteur', 'High Jump', 'Femme', True, 1),
('Perche', 'Pole Vault', 'Femme', True, 1),
('Longueur', 'Long Jump', 'Femme', True, 1),
('Triple saut', 'Triple Jump', 'Femme', True, 1),
('Poids', 'Shot Put', 'Femme', True, 1),
('Disque', 'Discus Throw', 'Femme', True, 1),
('Marteau', 'Hammer Throw', 'Femme', True, 1),
('Javelot', 'Javelin Throw', 'Femme', True, 1),
('Heptathlon', 'Heptathlon', 'Femme', True, 1),
('4x400m', '4 × 400 metres Relay', 'Mixte', False, 1),
('Skiff', 'Single Sculls', 'Homme', True, 2),
('Deux de couple', 'Double Sculls', 'Homme', False, 2),
('4 de couple', 'Quadruple Sculls', 'Homme', False, 2),
('Deux sans barreur', 'Coxless Pairs', 'Homme', False, 2),
('4 sans barreur', 'Coxless Fours', 'Homme', False, 2),
('Huit', 'Eights', 'Homme', False, 2),
('Deux de couple poids légers', 'Lightweight Double Sculls', 'Homme', False, 2),
('Skiff', 'Single Sculls', 'Femme', True, 2),
('Deux de couple', 'Double Sculls', 'Femme', False, 2),
('4 de couple', 'Quadruple Sculls', 'Femme', False, 2),
('Deux sans barreuse', 'Coxless Pairs', 'Femme', False, 2),
('4 sans barreuse', 'Coxless Fours', 'Femme', False, 2),
('Huit', 'Eights', 'Femme', False, 2),
('Deux de couple poids légers', 'Lightweight Double Sculls', 'Femme', False, 2),
('Simple', 'Singles', 'Homme', True, 3),
('Double', 'Doubles', 'Homme', False, 3),
('Simple', 'Singles', 'Femme', True, 3),
('Double', 'Doubles', 'Femme', False, 3),
('Double', 'Doubles', 'Mixte', False, 3),
('Basketball', 'Basketball', 'Homme', False, 4),
('Basketball', 'Basketball', 'Femme', False, 4),
('Basket 3x3', '3x3 Basketball', 'Homme', False, 5),
('Basket 3x3', '3x3 Basketball', 'Femme', False, 5),
('Mouche (48-52 kilogrammes)', 'Flyweight (48-52 kilograms)', 'Homme', True, 6),
('Plume (52-57 kilogrammes)', 'Featherweight (52-57 kilograms)', 'Homme', True, 6),
('Léger (57-63 kilogrammes)', 'Lightweight (57-63 kilograms)', 'Homme', True, 6),
('Mi-Moyen (63-69 kilogrammes)', 'Welterweight (63-69 kilograms)', 'Homme', True, 6),
('Moyen (69-75 kilogrammes)', 'Middleweight (69-75 kilograms)', 'Homme', True, 6),
('Mi-Lourd (75-81 kilogrammes)', 'Light-Heavyweight (75-81 kilograms)', 'Homme', True, 6),
('Lourd (81-91 kilogrammes)', 'Heavyweight (81-91 kilograms)', 'Homme', True, 6),
('Super-Lourd (>91 kilogrammes)', 'Super-Heavyweight (>91 kilograms)', 'Homme', True, 6),
('Mouche (48-51 kilogrammes)', 'Flyweight (48-51 kilograms)', 'Femme', True, 6),
('Plume (54-57 kilogrammes)', 'Featherweight (54-57 kilograms)', 'Femme', True, 6),
('Léger (57-60 kilogrammes)', 'Lightweight (57-60 kilograms)', 'Femme', True, 6),
('Mi-Moyen (64-69 kilogrammes)', 'Welterweight (64-69 kilograms)', 'Femme', True, 6),
('Moyen (69-75 kilogrammes)', 'Middleweight (69-75 kilograms)', 'Femme', True, 6),
('K1 200m', 'Kayak Singles, 200 metres', 'Homme', True, 7),
('K1 1000m', 'Kayak Singles, 1,000 metres', 'Homme', True, 7),
('K2 1000m', 'Kayak Doubles, 1,000 metres', 'Homme', False, 7),
('K4 500m', 'Kayak Fours, 500 metres', 'Homme', False, 7),
('C1 1000m', 'Canadian Singles, 1,000 metres', 'Homme', True, 7),
('C2 1000m', 'Canadian Doubles, 1,000 metres', 'Homme', False, 7),
('K1 200m', 'Kayak Singles, 200 metres', 'Femme', True, 7),
('K1 500m', 'Kayak Singles, 500 metres', 'Femme', True, 7),
('K2 500m', 'Kayak Doubles, 500 metres', 'Femme', False, 7),
('K4 500m', 'Kayak Fours, 500 metres', 'Femme', False, 7),
('C1 200m', 'Canadian Singles, 200 metres', 'Femme', True, 7),
('C2 500m', 'Canadian Doubles, 500 metres', 'Femme', False, 7),
('Slalom k1', 'Kayak Singles, Slalom', 'Homme', True, 8),
('Slalom c1', 'Canadian Singles, Slalom', 'Homme', True, 8),
('Slalom k1', 'Kayak Singles, Slalom', 'Femme', True, 8),
('Slalom c1', 'Canadian Singles, Slalom', 'Femme', True, 8),
('Vitesse', 'Sprint', 'Homme', True, 9),
('Keirin', 'Keirin', 'Homme', True, 9),
('Vitesse par équipes', 'Team Sprint', 'Homme', False, 9),
('Poursuite par équipes', 'Team Pursuit, 4,000 metres', 'Homme', False, 9),
('Américaine', 'Madison', 'Homme', False, 9),
('Omnium', 'Omnium', 'Homme', True, 9),
('Vitesse', 'Sprint', 'Femme', True, 9),
('Keirin', 'Keirin', 'Femme', True, 9),
('Vitesse par équipes', 'Team Sprint', 'Femme', False, 9),
('Poursuite par équipes', 'Team Pursuit, 4,000 metres', 'Femme', False, 9),
('Omnium', 'Omnium', 'Femme', True, 9),
('Américaine', 'Madison', 'Femme', False, 9),
('Course sur Route, Individuel', 'Road Race, Individual', 'Homme', True, 10),
('Contre-la-Montre Individuel', 'Individual Time Trial', 'Homme', True, 10),
('Course sur Route, Individuel', 'Road Race, Individual', 'Femme', True, 10),
('Contre-la-Montre Individuel', 'Individual Time Trial', 'Femme', True, 10),
('Park', 'Park', 'Homme', True, 11),
('Park', 'Park', 'Femme', True, 11),
('Course', 'BMX', 'Homme', True, 12),
('Course', 'BMX', 'Femme', True, 12),
('Cross-country', 'Cross-Country', 'Homme', True, 13),
('Cross-country', 'Cross-Country', 'Femme', True, 13),
('Fleuret', 'Foil, Individual', 'Homme', True, 14),
('Fleuret par équipes', 'Foil, Team', 'Homme', False, 14),
('Épée', 'Épée, Individual', 'Homme', True, 14),
('Epée par équipes', 'Épée, Team', 'Homme', False, 14),
('Sabre', 'Sabre, Individual', 'Homme', True, 14),
('Sabre par équipes', 'Sabre, Team', 'Homme', False, 14),
('Fleuret', 'Foil, Individual', 'Femme', True, 14),
('Fleuret par équipes', 'Foil, Team', 'Femme', False, 14),
('Épée', 'Épée, Individual', 'Femme', True, 14),
('Epée par équipes', 'Épée, Team', 'Femme', False, 14),
('Sabre', 'Sabre, Individual', 'Femme', True, 14),
('Sabre par équipes', 'Sabre, Team', 'Femme', False, 14),
('Football', 'Football', 'Homme', False, 15),
('Football', 'Football', 'Femme', False, 15),
('Individuel', 'Individual', 'Homme', True, 16),
('Individuel', 'Individual', 'Femme', True, 16),
('Concours général individuel', 'Individual All-Around', 'Homme', True, 17),
('Par équipes', 'Team All-Around', 'Homme', False, 17),
('Sol', 'Floor Exercise', 'Homme', True, 17),
('Saut', 'Horse Vault', 'Homme', True, 17),
('Barres parallèles', 'Parallel Bars', 'Homme', True, 17),
('Barre fixe', 'Horizontal Bar', 'Homme', True, 17),
('Anneaux', 'Rings', 'Homme', True, 17),
("Cheval d'arçons", 'Pommelled Horse', 'Homme', True, 17),
('Concours général individuel', 'Individual All-Around', 'Femme', True, 17),
('Par équipes', 'Team All-Around', 'Femme', False, 17),
('Sol', 'Floor Exercise', 'Femme', True, 17),
('Saut', 'Horse Vault', 'Femme', True, 17),
('Barres asymétriques', 'Uneven Bars', 'Femme', True, 17),
('Poutre', 'Balance Beam', 'Femme', True, 17),
('Concours individuel', 'Individual', 'Femme', True, 18),
('Concours par ensembles', 'Group', 'Femme', False, 18),
('Épreuve', 'Individual', 'Homme', True, 19),
('Épreuve', 'Individual', 'Femme', True, 19),
('Moins de 61 kg', 'Featherweight (≤61 kilograms)', 'Homme', True, 20),
('Moins de 67 kg', 'Lightweight (≤67 kilograms)', 'Homme', True, 20),
('Moins de 73 kg', 'Middleweight (≤73 kilograms)', 'Homme', True, 20),
('Moins de 81 kg', 'Light-Heavyweight (≤81 kilograms)', 'Homme', True, 20),
('Moins de 96 kg', 'Middle-Heavyweight (≤96 kilograms)', 'Homme', True, 20),
('Moins de 109 kg', 'Heavyweight (≤109 kilograms)', 'Homme', True, 20),
('Plus de 109 kg', 'Super-Heavyweight (>109 kilograms)', 'Homme', True, 20),
('Moins de 49 kg', 'Flyweight (≤49 kilograms)', 'Femme', True, 20),
('Moins de 55 kg', 'Featherweight (≤55 kilograms)', 'Femme', True, 20),
('Moins de 59 kg', 'Lightweight (≤59 kilograms)', 'Femme', True, 20),
('Moins de 64 kg', 'Middleweight (≤64 kilograms)', 'Femme', True, 20),
('Moins de 76 kg', 'Light-Heavyweight (≤76 kilograms)', 'Femme', True, 20),
('Moins de 87 kg', 'Heavyweight (≤87 kilograms)', 'Femme', True, 20),
('Plus de 87 kg', 'Super-Heavyweight (>87 kilograms)', 'Femme', True, 20),
('Handball', 'Handball', 'Homme', False, 21),
('Handball', 'Handball', 'Femme', False, 21),
('Hockey sur gazon', 'Hockey', 'Homme', False, 22),
('Hockey sur gazon', 'Hockey', 'Femme', False, 22),
('Moins de 60 kg', 'Extra-Lightweight (≤60 kilograms)', 'Homme', True, 23),
('Moins de 66 kg', 'Half-Lightweight (≤66 kilograms)', 'Homme', True, 23),
('Moins de 73 kg', 'Lightweight (≤73 kilograms)', 'Homme', True, 23),
('Moins de 81 kg', 'Half-Middleweight (≤81 kilograms)', 'Homme', True, 23),
('Moins de 90 kg', 'Middleweight (≤90 kilograms)', 'Homme', True, 23),
('Moins de 100 kg', 'Half-Heavyweight (≤100 kilograms)', 'Homme', True, 23),
('Plus de 100 kg', 'Heavyweight (>100 kilograms)', 'Homme', True, 23),
('Moins de 48 kg', 'Extra-Lightweight (≤48 kilograms)', 'Femme', True, 23),
('Moins de 52 kg', 'Half-Lightweight (≤52 kilograms)', 'Femme', True, 23),
('Moins de 57 kg', 'Lightweight (≤57 kilograms)', 'Femme', True, 23),
('Moins de 63 kg', 'Half-Middleweight (≤63 kilograms)', 'Femme', True, 23),
('Moins de 70 kg', 'Middleweight (≤70 kilograms)', 'Femme', True, 23),
('Moins de 78 kg', 'Half-Heavyweight (≤78 kilograms)', 'Femme', True, 23),
('Plus de 78 kg', 'Heavyweight (>78 kilograms)', 'Femme', True, 23),
('Par équipes', 'Team', 'Mixte', False, 23),
('Gréco romaine moins de 60 kg', 'Featherweight, Greco-Roman (≤60 kilograms)', 'Homme', True, 24),
('Gréco romaine moins de 67 kg', 'Welterweight, Greco-Roman (≤67 kilograms)', 'Homme', True, 24),
('Gréco romaine moins de 77 kg', 'Middleweight, Greco-Roman (≤77 kilograms)', 'Homme', True, 24),
('Gréco romaine moins de 87 kg', 'Light-Heavyweight, Greco-Roman (≤87 kilograms)', 'Homme', True, 24),
('Gréco romaine moins de 97 kg', 'Heavyweight, Greco-Roman (≤97 kilograms)', 'Homme', True, 24),
('Gréco romaine moins de 130 kg', 'Super-Heavyweight, Greco-Roman (≤130 kilograms)', 'Homme', True, 24),
('Libre moins de 57 kg', 'Featherweight, Freestyle (≤57 kilograms)', 'Homme', True, 24),
('Libre moins de 65 kg', 'Welterweight, Freestyle (≤65 kilograms)', 'Homme', True, 24),
('Libre moins de 74 kg', 'Middleweight, Freestyle (≤74 kilograms)', 'Homme', True, 24),
('Libre moins de 86 kg', 'Light-Heavyweight, Freestyle (≤86 kilograms)', 'Homme', True, 24),
('Libre moins de 97 kg', 'Heavyweight, Freestyle (≤97 kilograms)', 'Homme', True, 24),
('Libre moins de 125 kg', 'Super-Heavyweight, Freestyle (≤125 kilograms)', 'Homme', True, 24),
('Libre moins de 50 kg', 'Flyweight, Freestyle (≤50 kilograms)', 'Femme', True, 24),
('Libre moins de 53 kg', 'Featherweight, Freestyle (≤53 kilograms)', 'Femme', True, 24),
('Libre moins de 57 kg', 'Lightweight, Freestyle (≤57 kilograms)', 'Femme', True, 24),
('Libre moins de 62 kg', 'Middleweight, Freestyle (≤62 kilograms)', 'Femme', True, 24),
('Libre moins de 68 kg', 'Light-Heavyweight, Freestyle (≤68 kilograms)', 'Femme', True, 24),
('Libre moins de 76 kg', 'Heavyweight, Freestyle (≤76 kilograms)', 'Femme', True, 24),
('Individuel', 'Individual', 'Homme', True, 25),
('Individuel', 'Individual', 'Femme', True, 25),
('Rugby à Sept', 'Rugby Sevens', 'Homme', False, 26),
('Rugby à Sept', 'Rugby Sevens', 'Femme', False, 26),
('50m nage libre', '50 metres Freestyle', 'Homme', True, 27),
('100m nage libre', '100 metres Freestyle', 'Homme', True, 27),
('200m nage libre', '200 metres Freestyle', 'Homme', True, 27),
('400m nage libre', '400 metres Freestyle', 'Homme', True, 27),
('800m nage libre', '800 metres Freestyle', 'Homme', True, 27),
('1500m nage libre', '1,500 metres Freestyle', 'Homme', True, 27),
('Relais 4x100m nage libre', '4 x 100 metres Freestyle Relay', 'Homme', False, 27),
('Relais 4x200m nage libre', '4 x 200 metres Freestyle Relay', 'Homme', False, 27),
('100m dos', '100 metres Backstroke', 'Homme', True, 27),
('200m dos', '200 metres Backstroke', 'Homme', True, 27),
('100m brasse', '100 metres Breaststroke', 'Homme', True, 27),
('200m brasse', '200 metres Breaststroke', 'Homme', True, 27),
('100m papillon', '100 metres Butterfly', 'Homme', True, 27),
('200m papillon', '200 metres Butterfly', 'Homme', True, 27),
('200m 4 nages', '200 metres Individual Medley', 'Homme', True, 27),
('400m 4 nages', '400 metres Individual Medley', 'Homme', True, 27),
('Relais 4x100m 4 nages', '4 x 100 metres Medley Relay', 'Homme', False, 27),
('50m nage libre', '50 metres Freestyle', 'Femme', True, 27),
('100m nage libre', '100 metres Freestyle', 'Femme', True, 27),
('200m nage libre', '200 metres Freestyle', 'Femme', True, 27),
('400m nage libre', '400 metres Freestyle', 'Femme', True, 27),
('800m nage libre', '800 metres Freestyle', 'Femme', True, 27),
('1500m nage libre', '1,500 metres Freestyle', 'Femme', True, 27),
('Relais 4x100m nage libre', '4 x 100 metres Freestyle Relay', 'Femme', False, 27),
('Relais 4x200m nage libre', '4 x 200 metres Freestyle Relay', 'Femme', False, 27),
('100m dos', '100 metres Backstroke', 'Femme', True, 27),
('200m dos', '200 metres Backstroke', 'Femme', True, 27),
('100m brasse', '100 metres Breaststroke', 'Femme', True, 27),
('200m brasse', '200 metres Breaststroke', 'Femme', True, 27),
('100m papillon', '100 metres Butterfly', 'Femme', True, 27),
('200m papillon', '200 metres Butterfly', 'Femme', True, 27),
('200m 4 nages', '200 metres Individual Medley', 'Femme', True, 27),
('400m 4 nages', '400 metres Individual Medley', 'Femme', True, 27),
('Relais 4x100m 4 nages', '4 x 100 metres Medley Relay', 'Femme', False, 27),
('Relais 4x100m 4 nages mixte', '4 x 100 metres Medley Relay', 'Mixte', False, 27),
('Duo', 'Duet', 'Femme', False, 28),
('Par équipes', 'Team', 'Femme', False, 28),
('10 km', '10 kilometres Open Water', 'Homme', True, 29),
('10 km', '10 kilometres Open Water', 'Femme', True, 29),
('Tremplin 3m', 'Springboard', 'Homme', True, 30),
('Haut vol', 'Platform', 'Homme', True, 30),
('Tremplin 3m synchronisé', 'Synchronized Springboard', 'Homme', False, 30),
('Haut vol synchronisé', 'Synchronized Platform', 'Homme', False, 30),
('Tremplin 3m', 'Springboard', 'Femme', True, 30),
('Haut vol', 'Platform', 'Femme', True, 30),
('Tremplin 3m synchronisé', 'Synchronized Springboard', 'Femme', False, 30),
('Haut vol synchronisé', 'Synchronized Platform', 'Femme', False, 30),
('Water Polo', 'Water Polo', 'Homme', False, 31),
('Water Polo', 'Water Polo', 'Femme', False, 31),
('Dressage individuel', 'Individual', 'Mixte', True, 71),
('Équipe', 'Team', 'Mixte', False, 71),
('Concours complet individuel', 'Individual', 'Mixte', True, 72),
('Équipe', 'Team', 'Mixte', False, 72),
("Saut d'obstacles individuel", 'Individual', 'Mixte', True, 73),
('Équipe', 'Team', 'Mixte', False, 73),
('Moins de 58 kg', 'Flyweight (≤58 kilograms)', 'Homme', True, 33),
('Moins de 68 kg', 'Featherweight (≤68 kilograms)', 'Homme', True, 33),
('Moins de 80 kg', 'Welterweight (≤80 kilograms)', 'Homme', True, 33),
('Plus de 80 kg', 'Heavyweight (>80 kilograms)', 'Homme', True, 33),
('Moins de 49 kg', 'Flyweight (≤49 kilograms)', 'Femme', True, 33),
('Moins de 57 kg', 'Featherweight (≤57 kilograms)', 'Femme', True, 33),
('Moins de 67 kg', 'Welterweight (≤67 kilograms)', 'Femme', True, 33),
('Plus de 67 kg', 'Heavyweight (>67 kilograms)', 'Femme', True, 33),
('Simple', 'Singles', 'Homme', True, 34),
('Double', 'Doubles', 'Homme', False, 34),
('Simple', 'Singles', 'Femme', True, 34),
('Double', 'Doubles', 'Femme', False, 34),
('Double', 'Doubles', 'Mixte', False, 34),
('Simple', 'Singles', 'Homme', True, 35),
('Par équipes', 'Team', 'Homme', False, 35),
('Simple', 'Singles', 'Femme', True, 35),
('Par équipes', 'Team', 'Femme', False, 35),
('Double', 'Doubles', 'Mixte', False, 35),
('Pistolet 10m', 'Air Pistol, 10 metres', 'Homme', True, 36),
('Pistolet 25m vitesse olympique', 'Rapid-Fire Pistol, 25 metres', 'Homme', True, 36),
('Carabine 10m', 'Air Rifle, 10 metres', 'Homme', True, 36),
('Carabine 50m 3 positions', 'Small-Bore Rifle, Three Positions, 50 metres', 'Homme', True, 36),
('Fosse olympique', 'Trap', 'Homme', True, 36),
('Skeet', 'Skeet', 'Homme', True, 36),
('Pistolet 10m', 'Air Pistol, 10 metres', 'Femme', True, 36),
('Pistolet 25m', 'Sporting Pistol, 25 metres', 'Femme', True, 36),
('Carabine 10m', 'Air Rifle, 10 metres', 'Femme', True, 36),
('Carabine 50m 3 positions', 'Small-Bore Rifle, Three Positions, 50 metres', 'Femme', True, 36),
('Fosse olympique', 'Trap', 'Femme', True, 36),
('Skeet', 'Skeet', 'Femme', True, 36),
('Pistolet 10m par équipes', 'Air Pistol, 10 metres, Team', 'Mixte', False, 36),
('Carabine 10m par équipes', 'Air Rifle, 10 metres, Team', 'Mixte', False, 36),
('Fosse olympique par équipes', 'Trap, Team', 'Mixte', False, 36),
('Epreuve individuelle', 'Individual', 'Homme', True, 37),
('Epreuve par équipes', 'Team', 'Homme', False, 37),
('Epreuve individuelle', 'Individual', 'Femme', True, 37),
('Epreuve par équipes', 'Team', 'Femme', False, 37),
('Épreuve', 'Team', 'Mixte', False, 37),
('Distance olympique', 'Olympic Distance', 'Homme', True, 38),
('Distance olympique', 'Olympic Distance', 'Femme', True, 38),
('Relais', 'Relay', 'Mixte', False, 38),
('Planche à voile', 'Windsurfer (Neil Pryde RS:X)', 'Homme', True, 39),
('Laser', 'One Person Dinghy (Laser)', 'Homme', True, 39),
('470', 'Two Person Dinghy (470)', 'Homme', False, 39),
('49er', 'Skiff (49er)', 'Homme', False, 39),
('Finn', 'One Person Heavyweight Dinghy (Finn)', 'Homme', True, 39),
('Planche à voile', 'Windsurfer (Neil Pryde RS:X)', 'Femme', True, 39),
('Laser radial', 'One Person Dinghy (Laser Radial)', 'Femme', True, 39),
('470', 'Two Person Dinghy (470)', 'Femme', False, 39),
('49erfx', 'Skiff (49er FX)', 'Femme', False, 39),
('Nacra 17', 'Multihull (Nacra 17)', 'Mixte', False, 39),
('Volley-ball', 'Volleyball', 'Homme', False, 40),
('Volley-ball', 'Volleyball', 'Femme', False, 40),
('Beach Volleyball', 'Beach Volleyball', 'Homme', False, 41),
('Beach Volleyball', 'Beach Volleyball', 'Femme', False, 41),
('Battle B-girls', 'B-Girls', 'Femme', TRUE, 42),
('Battle B-boys', 'B-Boys', 'Homme', TRUE, 42),
('Combiné (vitesse-bloc-difficulté)', 'Combined', 'Homme', True, 43),
('Combiné (vitesse-bloc-difficulté)', 'Combined', 'Femme', True, 43),
('Street', 'Street', 'Homme', True, 44),
('Park', 'Park', 'Homme', True, 44),
('Street', 'Street', 'Femme', True, 44),
('Park', 'Park', 'Femme', True, 44),
('Moins de 78 kg', 'Featherweight, Freestyle (≤57 kilograms)', 'Homme', True, 44),
('Moins de 78 kg', 'Welterweight, Freestyle (≤65 kilograms)', 'Homme', True, 44),
('Moins de 78 kg', 'Middleweight, Freestyle (≤74 kilograms)', 'Homme', True, 44),
('Moins de 78 kg', 'Light-Heavyweight, Freestyle (≤86 kilograms)', 'Homme', True, 44),
('Moins de 78 kg', 'Heavyweight, Freestyle (≤97 kilograms)', 'Homme', True, 44),
('Moins de 78 kg', 'Super-Heavyweight, Freestyle (≤125 kilograms)', 'Homme', True, 44),
('Moins de 78 kg', 'Flyweight, Freestyle (≤50 kilograms)', 'Femme', True, 44),
('Moins de 78 kg', 'Featherweight, Freestyle (≤53 kilograms)', 'Femme', True, 44),
('Moins de 78 kg', 'Lightweight, Freestyle (≤57 kilograms)', 'Femme', True, 44),
('Moins de 78 kg', 'Middleweight, Freestyle (≤62 kilograms)', 'Femme', True, 44),
('Moins de 78 kg', 'Light-Heavyweight, Freestyle (≤68 kilograms)', 'Femme', True, 44),
('Moins de 78 kg', 'Heavyweight, Freestyle (≤76 kilograms)', 'Femme', True, 44),
('Planche courte', 'Shortboard', 'Homme', True, 45),
('Planche courte', 'Shortboard', 'Femme', True, 45),
('Baseball', 'Baseball', 'Homme', True, 69),
('Softball', 'Softball', 'Femme', True, 70),
('Kata', 'Kata', 'Homme', True, 74),
('Moins de 67 kg', 'Kumite, ≤67 kg', 'Homme', True, 74),
('Moins de 75 kg', 'Kumite, ≤75 kg', 'Homme', True, 74),
('Plus de 75 kg', 'Kumite, >75 kg', 'Homme', True, 74),
('Kata', 'Kata', 'Femme', True, 74),
('Moins de 55 kg', 'Kumite, ≤55 kg', 'Femme', True, 74),
('Moins de 61 kg', 'Kumite, ≤61 kg', 'Femme', True, 74),
('Plus de 61 kg', 'Kumite, >61 kg', 'Femme', True, 74);